# Default values for workspace-mcp
replicaCount: 1

image:
  repository: workspace-mcp
  pullPolicy: IfNotPresent
  # Uses Chart.AppVersion if not specified
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext:
  fsGroup: 1000

securityContext:
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: false
  runAsNonRoot: true
  runAsUser: 1000

service:
  type: ClusterIP
  port: 8000
  targetPort: 8000

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: workspace-mcp.local
      paths:
        - path: /
          pathType: Prefix
  tls: []
  #  - secretName: workspace-mcp-tls
  #    hosts:
  #      - workspace-mcp.local

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

# Environment variables for the application
env:
  # Server configuration
  WORKSPACE_MCP_PORT: "8000"
  # Set the base URI for your Kubernetes environment
  # For internal cluster access: "http://{{ include "workspace-mcp.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local"
  # For external access: "https://your-domain.com" or "http://your-ingress-host"
  WORKSPACE_MCP_BASE_URI: ""
  
  # External URL for reverse proxy setups (e.g., "https://your-domain.com")
  # If set, this overrides the base_uri:port combination for OAuth endpoints
  WORKSPACE_EXTERNAL_URL: ""
  
  # OAuth 2.1 support
  MCP_ENABLE_OAUTH21: "false"
  
  # Development only - set to "1" for local development
  OAUTHLIB_INSECURE_TRANSPORT: "0"
  
  # Optional: Google Custom Search
  # GOOGLE_PSE_API_KEY: ""
  # GOOGLE_PSE_ENGINE_ID: ""

# Secret configuration for sensitive data
secrets:
  # Google OAuth credentials (required)
  googleOAuth:
    # Set these values or create secret manually
    clientId: ""
    clientSecret: ""
    # Optional: default user email for single-user setups
    userEmail: ""

# Tool selection - specify which Google Workspace tools to enable
tools:
  enabled: []
  # Available tools: gmail, drive, calendar, docs, sheets, chat, forms, slides, tasks, search
  # Example: ["gmail", "drive", "calendar"]
  # Leave empty to enable all tools

# Tool tier selection - alternative to specifying individual tools
# Options: core, extended, complete
# Leave empty to use default or tools.enabled configuration
toolTier: ""

# Single-user mode configuration
singleUserMode: false

# Command configuration
command:
  # Set disableArgs to true to remove the args section entirely (uses Dockerfile defaults)
  disableArgs: false
  # Override the entire command if needed
  override: []

# Health check configuration
healthCheck:
  enabled: true
  path: /health
  initialDelaySeconds: 30
  periodSeconds: 30
  timeoutSeconds: 10
  successThreshold: 1
  failureThreshold: 3

# Pod disruption budget
podDisruptionBudget:
  enabled: false
  minAvailable: 1
  # maxUnavailable: 1

# Network policies
networkPolicy:
  enabled: false
  ingress: []
  egress: []